application:
  name: '@pom.artifactId@'
  description: '@pom.description@'
  version: '@pom.version@'

server.port: 8080

# Log configuration
logging.file: log/customerapi.log

#oauth:
#  enabled: true
#  all-in-one: true

# H2 console configuration
spring.h2.console:
  enabled: true
  path: /h2

# DataSource configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customerapi
    username: customerapi
    password: customerapi
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      minimumIdle: 10
      maximumPoolSize: 10
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
    properties.hibernate.jdbc.lob.non_contextual_creation: true

# Jackson configuration
spring.jackson:
  default-property-inclusion: non_null
  deserialization.adjust-dates-to-context-time-zone: false
