version: '3'

services:
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: customerapi
      POSTGRES_PASSWORD: customerapi
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: