version: '3'

services:
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: authorizationserver
      POSTGRES_PASSWORD: authorizationserver
    expose:
      - 5432
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: