/*
Script generated by Aqua Data Studio 16.0.5-9 on Jan-20-2018 04:38:46 PM
Database: customerapi
Schema: <All Schemas>
Objects: TABLE, VIEW, PROCEDURE, FUNCTION, TRIGGER, EVENT
*/
CREATE TABLE user_customer_api (
    id           int(11) AUTO_INCREMENT NOT NULL,
    name         varchar(255) NULL,
    email        varchar(255) NULL,
    password     varchar(255) NULL,
    PRIMARY KEY(id)
)
